import { LemmingGift } from "../types"
import { LevelMapDetail, SingleCharacterAnimation } from "../maps/types"
import { Level } from "../levels/level"
import { LevelMetadata } from "../../shared/src/wasm-safe"

      export class Level_AUTO_1_SOON extends Level {

        constructor() {
          super('AUTO_1_SOON', 'AUTO', 41, 28, mapDetail)
      
          this.setSkillQuantity(LemmingGift.ClimbingBoots, 255)
this.setSkillQuantity(LemmingGift.Umbrella, 255)
this.setSkillQuantity(LemmingGift.Bomb, 255)
this.setSkillQuantity(LemmingGift.Block, 255)
this.setSkillQuantity(LemmingGift.BrickSack, 255)
this.setSkillQuantity(LemmingGift.Hammer, 255)
this.setSkillQuantity(LemmingGift.Pickaxe, 255)
this.setSkillQuantity(LemmingGift.Shovel, 255)
        }
      }
    const mapDetail = new LevelMapDetail([])
mapDetail.meta = new LevelMetadata("STARTING_SOON",1, "SOON", "AUTO", "grassland", 41, 28)
mapDetail.tiles.push("__________________________________________________________________________")
mapDetail.tiles.push("|                                                                        |")
mapDetail.tiles.push("|                                                                        |")
mapDetail.tiles.push("|                                                                        |")
mapDetail.tiles.push("|                                                                        |")
mapDetail.tiles.push("|                                                                        |")
mapDetail.tiles.push("|                                                                        |")
mapDetail.tiles.push("|                                                                        |")
mapDetail.tiles.push("|                                                                        |")
mapDetail.tiles.push("|                                                                        |")
mapDetail.tiles.push("|                                                                        |")
mapDetail.tiles.push("|                                                                        |")
mapDetail.tiles.push("|                                                                        |")
mapDetail.tiles.push("|                                                                        |")
mapDetail.tiles.push("|                                                                        |")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|               G                                                        |")
mapDetail.tiles.push("|               G                                                        |")
mapDetail.tiles.push("|               G                                                        |")
mapDetail.tiles.push("|               G     GGG    GGG    G    GGG     GGG      GG             |")
mapDetail.tiles.push("|               G    G        G    G G   G G      G      G               |")
mapDetail.tiles.push("|               G      G      G    GGG   GG       G       G              |")
mapDetail.tiles.push("|               G    GG       G    G G   G G      G     GG               |")
mapDetail.tiles.push("|               G                                                        |")
mapDetail.tiles.push("|               G                                                        |")
mapDetail.tiles.push("|               G                                                        |")
mapDetail.tiles.push("|               G              GG                                        |")
mapDetail.tiles.push("|               G             G       GG     GG      GGG                 |")
mapDetail.tiles.push("|               G              G     G  G   G  G    G   G                |")
mapDetail.tiles.push("|               G            GG       GG     GG     G   G                |")
mapDetail.tiles.push("|               G                                                        |")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG                             E   |")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.customAnimations.set("1,31", "grassland_grass")
mapDetail.customAnimations.set("2,31", "grassland_grass")
mapDetail.customAnimations.set("3,31", "grassland_grass")
mapDetail.customAnimations.set("4,31", "grassland_grass")
mapDetail.customAnimations.set("5,31", "grassland_grass")
mapDetail.customAnimations.set("6,31", "grassland_grass")
mapDetail.customAnimations.set("7,31", "grassland_grass")
mapDetail.customAnimations.set("8,31", "grassland_grass")
mapDetail.customAnimations.set("9,31", "grassland_grass")
mapDetail.customAnimations.set("10,31", "grassland_grass")
mapDetail.customAnimations.set("11,31", "grassland_grass")
mapDetail.customAnimations.set("12,31", "grassland_grass")
mapDetail.customAnimations.set("13,31", "grassland_grass")
mapDetail.customAnimations.set("14,31", "grassland_grass")
mapDetail.customAnimations.set("15,31", "grassland_grass")
mapDetail.customAnimations.set("16,31", "grassland_grass")
mapDetail.customAnimations.set("17,31", "grassland_grass")
mapDetail.customAnimations.set("18,31", "grassland_grass")
mapDetail.customAnimations.set("19,31", "grassland_grass")
mapDetail.customAnimations.set("20,31", "grassland_grass")
mapDetail.customAnimations.set("21,31", "grassland_grass")
mapDetail.customAnimations.set("22,31", "grassland_grass")
mapDetail.customAnimations.set("23,31", "grassland_grass")
mapDetail.customAnimations.set("24,31", "grassland_grass")
mapDetail.customAnimations.set("25,31", "grassland_grass")
mapDetail.customAnimations.set("26,31", "grassland_grass")
mapDetail.customAnimations.set("27,31", "grassland_grass")
mapDetail.customAnimations.set("28,31", "grassland_grass")
mapDetail.customAnimations.set("29,31", "grassland_grass")
mapDetail.customAnimations.set("30,31", "grassland_grass")
mapDetail.customAnimations.set("31,31", "grassland_grass")
mapDetail.customAnimations.set("32,31", "grassland_grass")
mapDetail.customAnimations.set("33,31", "grassland_grass")
mapDetail.customAnimations.set("34,31", "grassland_grass")
mapDetail.customAnimations.set("35,31", "grassland_grass")
mapDetail.customAnimations.set("36,31", "grassland_grass")
mapDetail.customAnimations.set("37,31", "grassland_grass")
mapDetail.customAnimations.set("38,31", "grassland_grass")
mapDetail.customAnimations.set("39,31", "grassland_grass")
mapDetail.customAnimations.set("40,32", "grassland_grass")
mapDetail.customAnimations.set("41,32", "grassland_grass")
mapDetail.customAnimations.set("42,32", "grassland_grass")
mapDetail.customAnimations.set("43,32", "grassland_grass")
mapDetail.customAnimations.set("44,32", "grassland_grass")
mapDetail.customAnimations.set("45,32", "grassland_grass")
mapDetail.customAnimations.set("46,32", "grassland_grass")
mapDetail.customAnimations.set("47,32", "grassland_grass")
mapDetail.customAnimations.set("48,32", "grassland_grass")
mapDetail.customAnimations.set("49,32", "grassland_grass")
mapDetail.customAnimations.set("50,32", "grassland_grass")
mapDetail.customAnimations.set("51,32", "grassland_grass")
mapDetail.customAnimations.set("52,32", "grassland_grass")
mapDetail.customAnimations.set("53,32", "grassland_grass")
mapDetail.customAnimations.set("54,32", "grassland_grass")
mapDetail.customAnimations.set("55,32", "grassland_grass")
mapDetail.customAnimations.set("56,32", "grassland_grass")
mapDetail.customAnimations.set("57,32", "grassland_grass")
mapDetail.customAnimations.set("58,32", "grassland_grass")
mapDetail.customAnimations.set("59,32", "grassland_grass")
mapDetail.customAnimations.set("60,32", "grassland_grass")
mapDetail.customAnimations.set("61,32", "grassland_grass")
mapDetail.customAnimations.set("62,32", "grassland_grass")
mapDetail.customAnimations.set("63,32", "grassland_grass")
mapDetail.customAnimations.set("64,32", "grassland_grass")
mapDetail.customAnimations.set("65,32", "grassland_grass")
mapDetail.customAnimations.set("66,32", "grassland_grass")
mapDetail.customAnimations.set("67,32", "grassland_grass")
mapDetail.customAnimations.set("68,32", "grassland_grass")
mapDetail.customAnimations.set("69,32", "grassland_grass")
mapDetail.customAnimations.set("70,32", "grassland_grass")
mapDetail.customAnimations.set("71,32", "grassland_grass")
mapDetail.customAnimations.set("72,32", "grassland_grass")
mapDetail.customAnimations.set("69,31", "exit")
mapDetail.customAnimations.set("69,30", "EXIT_MIDDLE")
mapDetail.customAnimations.set("69,29", "EXIT_TOP")
mapDetail.customAnimations.set("68,31", "EXIT_SIDE")
mapDetail.customAnimations.set("68,30", "EXIT_SIDE")
mapDetail.customAnimations.set("68,29", "EXIT_FLAME")
mapDetail.customAnimations.set("70,31", "EXIT_SIDE")
mapDetail.customAnimations.set("70,30", "EXIT_SIDE")
mapDetail.customAnimations.set("70,29", "EXIT_FLAME")
mapDetail.defaultAnimations.set("'", "grassland_grass")
mapDetail.defaultAnimations.set("G", "grassland_ground")
