import { LemmingGift } from "../types"
import { LevelMapDetail, SingleCharacterAnimation } from "../maps/types"
import { Level } from "../levels/level"

      export class Level_fun_1_CAJJLDLBCS extends Level {

        constructor() {
          super('fun_1_CAJJLDLBCS', 'fun', 4, 1, mapDetail)
      
          this.setSkillQuantity(LemmingGift.Shovel, u8.MAX_VALUE)
          this.setSkillQuantity(LemmingGift.Block, 10)
          this.setSkillQuantity(LemmingGift.Bomb, 10)
          this.setSkillQuantity(LemmingGift.BrickSack, u8.MAX_VALUE)
          this.setSkillQuantity(LemmingGift.ClimbingBoots, 10)
          this.setSkillQuantity(LemmingGift.Hammer, 10)
          this.setSkillQuantity(LemmingGift.Pickaxe, 10)
          this.setSkillQuantity(LemmingGift.Umbrella, 10)
        }
      }
    const mapDetail = new LevelMapDetail([])
mapDetail.tiles.push("__________________________________________________________________________________________________")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG           GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGG                        GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGG                            GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGG                               GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGG                                    GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGG                                       GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGG                                       GGGGGGGGGGGGGGGGGGG GGGGGGGGGGGGGGGGGGGGGGG GGGG|")
mapDetail.tiles.push("|GGGGGGGGG                                       GGGGGGGGGGGGGGGGGGG  GGGGGGGGGGGGGGGGGGGGGG  GGG|")
mapDetail.tiles.push("|GGGGGGGGG                                       GGGGGGGGGGGGGGGGGG    GGGGGGGGGGGGGGGGGGGG    GG|")
mapDetail.tiles.push("|GGGGGGGGG                                       GGGGGGGGGGGGGG GGG    GGGGGGGGGGGGGGGG GGG    GG|")
mapDetail.tiles.push("|GGGGGGGGG                                       GGGGGGGGGGGGGG        GGGGGGGGGGGGGGGG        GG|")
mapDetail.tiles.push("|GGGGGGGGG                                       GGGGGGGGGGGGGG        GGGGGGGGGGGGGGGG        GG|")
mapDetail.tiles.push("|GGGGGGGGG                                       GGGGGGGGGGGGGG        GGGGGGGGGGGGGGGG        GG|")
mapDetail.tiles.push("|GGGGGGGGG                                      GGGGGGGGGGGGGGGG       GGGGGGGGGGGGGGGGG       GG|")
mapDetail.tiles.push("|GGGGGGGGG                                     GGGGGGGGGGGGGGGGGG      GGGGGGGGGGGGGGGGGG      GG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG     GGGGGGGGGGGGGGGGGGG     GG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG     GGGGGGGGGGGGGGGGGGG     GG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG     GGGGGGGGGGGGGGGGGGG     GGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG     GGGGGGGGGGGGGGGGGGG     GGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG    GGGGGGGGGGGGGGGGGGGG    GGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG      GGGGGGGGGGGGGGGGGG      GGG|")
mapDetail.tiles.push("|GGGGGGG   GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG       GGGGGGGGGGGGGGGGG       GGG|")
mapDetail.tiles.push("|GGGGGG               GGGGGGGGG    GGGGGGGGG                         GGGG                    GGGG|")
mapDetail.tiles.push("|GGGGG                                                               GGGG                    GGGG|")
mapDetail.tiles.push("|GGGGG                                                               GGGG                    GGGG|")
mapDetail.tiles.push("|GGGGG                                                              GGGGG                   GGGGG|")
mapDetail.tiles.push("|GGGGG                                                             GGGGGG                  GGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGG                              E        GGGGGGG        E        GGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG      GGGGGGGGGGGGGGGGGG      GGG|")
mapDetail.tiles.push("|GGGGGGG   GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG       GGGGGGGGGGGGGGGGG       GGG|")
mapDetail.tiles.push("|GGGGGG               GGGGGGGGG    GGGGGGGGG                         GGGG                    GGGG|")
mapDetail.tiles.push("|GGGGG                                                               GGGG                    GGGG|")
mapDetail.tiles.push("|GGGGG                                                               GGGG                    GGGG|")
mapDetail.tiles.push("|GGGGG                                                              GGGGG                   GGGGG|")
mapDetail.tiles.push("|GGGGG                                                             GGGGGG                  GGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGG                              E        GGGGGGG        E        GGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.defaultAnimations.set("G", "ground")
mapDetail.customAnimations.set("10,17", "grass")
mapDetail.customAnimations.set("11,17", "grass")
mapDetail.customAnimations.set("12,17", "grass")
mapDetail.customAnimations.set("13,17", "grass")
mapDetail.customAnimations.set("14,17", "grass")
mapDetail.customAnimations.set("15,17", "grass")
mapDetail.customAnimations.set("16,17", "grass")
mapDetail.customAnimations.set("17,17", "grass")
mapDetail.customAnimations.set("18,17", "grass")
mapDetail.customAnimations.set("19,17", "grass")
mapDetail.customAnimations.set("20,17", "grass")
mapDetail.customAnimations.set("21,17", "grass")
mapDetail.customAnimations.set("22,17", "grass")
mapDetail.customAnimations.set("23,17", "grass")
mapDetail.customAnimations.set("24,17", "grass")
mapDetail.customAnimations.set("25,17", "grass")
mapDetail.customAnimations.set("26,17", "grass")
mapDetail.customAnimations.set("27,17", "grass")
mapDetail.customAnimations.set("28,17", "grass")
mapDetail.customAnimations.set("29,17", "grass")
mapDetail.customAnimations.set("30,17", "grass")
mapDetail.customAnimations.set("31,17", "grass")
mapDetail.customAnimations.set("32,17", "grass")
mapDetail.customAnimations.set("33,17", "grass")
mapDetail.customAnimations.set("34,17", "grass")
mapDetail.customAnimations.set("35,17", "grass")
mapDetail.customAnimations.set("36,17", "grass")
mapDetail.customAnimations.set("37,17", "grass")
mapDetail.customAnimations.set("38,17", "grass")
mapDetail.customAnimations.set("39,17", "grass")
mapDetail.customAnimations.set("40,17", "grass")
mapDetail.customAnimations.set("41,17", "grass")
mapDetail.customAnimations.set("42,17", "grass")
mapDetail.customAnimations.set("43,17", "grass")
mapDetail.customAnimations.set("44,17", "grass")
mapDetail.customAnimations.set("45,17", "grass")
mapDetail.customAnimations.set("46,17", "grass")
mapDetail.customAnimations.set("6,29", "grass")
mapDetail.customAnimations.set("7,29", "grass")
mapDetail.customAnimations.set("8,29", "grass")
mapDetail.customAnimations.set("9,29", "grass")
mapDetail.customAnimations.set("0,29", "grass")
mapDetail.customAnimations.set("10,29", "grass")
mapDetail.customAnimations.set("11,29", "grass")
mapDetail.customAnimations.set("12,29", "grass")
mapDetail.customAnimations.set("13,29", "grass")
mapDetail.customAnimations.set("14,29", "grass")
mapDetail.customAnimations.set("15,29", "grass")
mapDetail.customAnimations.set("16,29", "grass")
mapDetail.customAnimations.set("17,29", "grass")
mapDetail.customAnimations.set("18,29", "grass")
mapDetail.customAnimations.set("19,29", "grass")
mapDetail.customAnimations.set("20,29", "grass")
mapDetail.customAnimations.set("21,29", "grass")
mapDetail.customAnimations.set("22,29", "grass")
mapDetail.customAnimations.set("23,29", "grass")
mapDetail.customAnimations.set("24,29", "grass")
mapDetail.customAnimations.set("25,29", "grass")
mapDetail.customAnimations.set("26,29", "grass")
mapDetail.customAnimations.set("27,30", "grass")
mapDetail.customAnimations.set("28,30", "grass")
mapDetail.customAnimations.set("29,30", "grass")
mapDetail.customAnimations.set("30,30", "grass")
mapDetail.customAnimations.set("31,30", "grass")
mapDetail.customAnimations.set("32,30", "grass")
mapDetail.customAnimations.set("33,30", "grass")
mapDetail.customAnimations.set("34,30", "grass")
mapDetail.customAnimations.set("35,30", "grass")
mapDetail.customAnimations.set("36,30", "grass")
mapDetail.customAnimations.set("37,30", "grass")
mapDetail.customAnimations.set("38,30", "grass")
mapDetail.customAnimations.set("39,30", "grass")
mapDetail.customAnimations.set("40,30", "grass")
mapDetail.customAnimations.set("41,30", "grass")
mapDetail.customAnimations.set("42,30", "grass")
mapDetail.customAnimations.set("43,30", "grass")
mapDetail.customAnimations.set("44,30", "grass")
mapDetail.customAnimations.set("45,30", "grass")
mapDetail.customAnimations.set("46,30", "grass")
mapDetail.customAnimations.set("47,30", "grass")
mapDetail.customAnimations.set("48,30", "grass")
mapDetail.customAnimations.set("49,30", "grass")
mapDetail.customAnimations.set("50,30", "grass")
mapDetail.customAnimations.set("51,30", "grass")
mapDetail.customAnimations.set("52,30", "grass")
mapDetail.customAnimations.set("53,30", "grass")
mapDetail.customAnimations.set("54,30", "grass")
mapDetail.customAnimations.set("55,30", "grass")
mapDetail.customAnimations.set("56,30", "grass")
mapDetail.customAnimations.set("57,30", "grass")
mapDetail.customAnimations.set("58,30", "grass")
mapDetail.customAnimations.set("59,30", "grass")
mapDetail.customAnimations.set("60,30", "grass")
mapDetail.customAnimations.set("61,30", "grass")
mapDetail.customAnimations.set("62,30", "grass")
mapDetail.customAnimations.set("63,30", "grass")
mapDetail.customAnimations.set("64,30", "grass")
mapDetail.customAnimations.set("65,30", "grass")
