import { LemmingGift } from "../types"
import { LevelMapDetail, SingleCharacterAnimation } from "../maps/types"
import { Level } from "../levels/level"
import { LevelMetadata } from "../../shared/src/wasm-safe"

      export class Level_fun_1_CAJJLDLBCS extends Level {

        constructor() {
          super('fun_1_CAJJLDLBCS', 'fun', 10, 1, mapDetail)
      
          this.setSkillQuantity(LemmingGift.ClimbingBoots, 10)
this.setSkillQuantity(LemmingGift.Umbrella, 10)
this.setSkillQuantity(LemmingGift.Bomb, 10)
this.setSkillQuantity(LemmingGift.Block, 10)
this.setSkillQuantity(LemmingGift.BrickSack, 255)
this.setSkillQuantity(LemmingGift.Hammer, 10)
this.setSkillQuantity(LemmingGift.Pickaxe, 10)
this.setSkillQuantity(LemmingGift.Shovel, 255)
        }
      }
    const mapDetail = new LevelMapDetail([])
mapDetail.meta = new LevelMetadata("Just dig!",1, "CAJJLDLBCS", "fun", "grassland", 10, 1)
mapDetail.tiles.push("__________________________________________________________________________")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG           GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGG                        GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGG                            GGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGG                               GGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGG                                    GGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGG                                       GGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGG                                       GGGGGGGGGGGGGGGGGGG GGGG|")
mapDetail.tiles.push("|GGGGGGGGG                                       GGGGGGGGGGGGGGGGGGG  GGG|")
mapDetail.tiles.push("|GGGGGGGGG                                       GGGGGGGGGGGGGGGGGG    GG|")
mapDetail.tiles.push("|GGGGGGGGG                                       GGGGGGGGGGGGGG GGG    GG|")
mapDetail.tiles.push("|GGGGGGGGG                                       GGGGGGGGGGGGGG        GG|")
mapDetail.tiles.push("|GGGGGGGGG                                       GGGGGGGGGGGGGG        GG|")
mapDetail.tiles.push("|GGGGGGGGG                                       GGGGGGGGGGGGGG        GG|")
mapDetail.tiles.push("|GGGGGGGGG                                      GGGGGGGGGGGGGGGG       GG|")
mapDetail.tiles.push("|GGGGGGGGG                                     GGGGGGGGGGGGGGGGGG      GG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG     GG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG     GG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG     GGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG     GGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG    GGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG      GGG|")
mapDetail.tiles.push("|GGGGGGG   GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG       GGG|")
mapDetail.tiles.push("|GGGGGG               GGGGGGGGG    GGGGGGGGG                         GGGG|")
mapDetail.tiles.push("|GGGGG                                                               GGGG|")
mapDetail.tiles.push("|GGGGG                                                               GGGG|")
mapDetail.tiles.push("|GGGGG                                                              GGGGG|")
mapDetail.tiles.push("|GGGGG                                                             GGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGG                              E        GGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.tiles.push("|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG|")
mapDetail.customAnimations.set("10,17", "grassland_grass")
mapDetail.customAnimations.set("11,17", "grassland_grass")
mapDetail.customAnimations.set("12,17", "grassland_grass")
mapDetail.customAnimations.set("13,17", "grassland_grass")
mapDetail.customAnimations.set("14,17", "grassland_grass")
mapDetail.customAnimations.set("15,17", "grassland_grass")
mapDetail.customAnimations.set("16,17", "grassland_grass")
mapDetail.customAnimations.set("17,17", "grassland_grass")
mapDetail.customAnimations.set("18,17", "grassland_grass")
mapDetail.customAnimations.set("19,17", "grassland_grass")
mapDetail.customAnimations.set("20,17", "grassland_grass")
mapDetail.customAnimations.set("21,17", "grassland_grass")
mapDetail.customAnimations.set("22,17", "grassland_grass")
mapDetail.customAnimations.set("23,17", "grassland_grass")
mapDetail.customAnimations.set("24,17", "grassland_grass")
mapDetail.customAnimations.set("25,17", "grassland_grass")
mapDetail.customAnimations.set("26,17", "grassland_grass")
mapDetail.customAnimations.set("27,17", "grassland_grass")
mapDetail.customAnimations.set("28,17", "grassland_grass")
mapDetail.customAnimations.set("29,17", "grassland_grass")
mapDetail.customAnimations.set("30,17", "grassland_grass")
mapDetail.customAnimations.set("31,17", "grassland_grass")
mapDetail.customAnimations.set("32,17", "grassland_grass")
mapDetail.customAnimations.set("33,17", "grassland_grass")
mapDetail.customAnimations.set("34,17", "grassland_grass")
mapDetail.customAnimations.set("35,17", "grassland_grass")
mapDetail.customAnimations.set("36,17", "grassland_grass")
mapDetail.customAnimations.set("37,17", "grassland_grass")
mapDetail.customAnimations.set("38,17", "grassland_grass")
mapDetail.customAnimations.set("39,17", "grassland_grass")
mapDetail.customAnimations.set("40,17", "grassland_grass")
mapDetail.customAnimations.set("41,17", "grassland_grass")
mapDetail.customAnimations.set("42,17", "grassland_grass")
mapDetail.customAnimations.set("43,17", "grassland_grass")
mapDetail.customAnimations.set("44,17", "grassland_grass")
mapDetail.customAnimations.set("45,17", "grassland_grass")
mapDetail.customAnimations.set("46,17", "grassland_grass")
mapDetail.customAnimations.set("6,29", "grassland_grass")
mapDetail.customAnimations.set("7,29", "grassland_grass")
mapDetail.customAnimations.set("8,29", "grassland_grass")
mapDetail.customAnimations.set("9,29", "grassland_grass")
mapDetail.customAnimations.set("0,29", "grassland_grass")
mapDetail.customAnimations.set("10,29", "grassland_grass")
mapDetail.customAnimations.set("11,29", "grassland_grass")
mapDetail.customAnimations.set("12,29", "grassland_grass")
mapDetail.customAnimations.set("13,29", "grassland_grass")
mapDetail.customAnimations.set("14,29", "grassland_grass")
mapDetail.customAnimations.set("15,29", "grassland_grass")
mapDetail.customAnimations.set("16,29", "grassland_grass")
mapDetail.customAnimations.set("17,29", "grassland_grass")
mapDetail.customAnimations.set("18,29", "grassland_grass")
mapDetail.customAnimations.set("19,29", "grassland_grass")
mapDetail.customAnimations.set("20,29", "grassland_grass")
mapDetail.customAnimations.set("21,29", "grassland_grass")
mapDetail.customAnimations.set("22,29", "grassland_grass")
mapDetail.customAnimations.set("23,29", "grassland_grass")
mapDetail.customAnimations.set("24,29", "grassland_grass")
mapDetail.customAnimations.set("25,29", "grassland_grass")
mapDetail.customAnimations.set("26,29", "grassland_grass")
mapDetail.customAnimations.set("27,30", "grassland_grass")
mapDetail.customAnimations.set("28,30", "grassland_grass")
mapDetail.customAnimations.set("29,30", "grassland_grass")
mapDetail.customAnimations.set("30,30", "grassland_grass")
mapDetail.customAnimations.set("31,30", "grassland_grass")
mapDetail.customAnimations.set("32,30", "grassland_grass")
mapDetail.customAnimations.set("33,30", "grassland_grass")
mapDetail.customAnimations.set("34,30", "grassland_grass")
mapDetail.customAnimations.set("35,30", "grassland_grass")
mapDetail.customAnimations.set("36,30", "grassland_grass")
mapDetail.customAnimations.set("37,30", "grassland_grass")
mapDetail.customAnimations.set("38,30", "grassland_grass")
mapDetail.customAnimations.set("39,30", "grassland_grass")
mapDetail.customAnimations.set("40,30", "grassland_grass")
mapDetail.customAnimations.set("41,30", "grassland_grass")
mapDetail.customAnimations.set("42,30", "grassland_grass")
mapDetail.customAnimations.set("43,30", "grassland_grass")
mapDetail.customAnimations.set("44,30", "grassland_grass")
mapDetail.customAnimations.set("45,30", "grassland_grass")
mapDetail.customAnimations.set("46,30", "grassland_grass")
mapDetail.customAnimations.set("47,30", "grassland_grass")
mapDetail.customAnimations.set("48,30", "grassland_grass")
mapDetail.customAnimations.set("49,30", "grassland_grass")
mapDetail.customAnimations.set("50,30", "grassland_grass")
mapDetail.customAnimations.set("51,30", "grassland_grass")
mapDetail.customAnimations.set("52,30", "grassland_grass")
mapDetail.customAnimations.set("53,30", "grassland_grass")
mapDetail.customAnimations.set("54,30", "grassland_grass")
mapDetail.customAnimations.set("55,30", "grassland_grass")
mapDetail.customAnimations.set("56,30", "grassland_grass")
mapDetail.customAnimations.set("57,30", "grassland_grass")
mapDetail.customAnimations.set("58,30", "grassland_grass")
mapDetail.customAnimations.set("59,30", "grassland_grass")
mapDetail.customAnimations.set("60,30", "grassland_grass")
mapDetail.customAnimations.set("61,30", "grassland_grass")
mapDetail.customAnimations.set("62,30", "grassland_grass")
mapDetail.customAnimations.set("63,30", "grassland_grass")
mapDetail.customAnimations.set("64,30", "grassland_grass")
mapDetail.customAnimations.set("65,30", "grassland_grass")
//mapDetail.trapTiles.set("39,16", "TRAP_PISTON")
mapDetail.defaultAnimations.set("'", "grassland_grass")
mapDetail.defaultAnimations.set("G", "grassland_ground")
